<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>StockAnalyzer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="stock_radar_cloud_deploy\**;新增資料夾\**" />
    <Content Remove="stock_radar_cloud_deploy\**;新增資料夾\**" />
    <EmbeddedResource Remove="stock_radar_cloud_deploy\**;新增資料夾\**" />
    <None Remove="stock_radar_cloud_deploy\**;新增資料夾\**" />
    <Content Update="Data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
